# Docker compose version syntax being used
version: "3.9"

services:
  # Name of service
  app:
    # Location of relavant Dockerfile for build
    build:
      context: .
      args:
        - DEV=true
    # Map ports - local:container
    ports:
      - "8000:8000"
    # Sync directories - local:container
    volumes:
      - "./app:/app"
    # Default command if none passed to docker-compose
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
